spring.datasource.url=${SUPABASE_URL_TRANSACTION_POOLER}
spring.datasource.username=${SUPABASE_USERNAME}
spring.datasource.password=${SUPABASE_PASSWORD}

# Emails
# Emails
app.email.enabled=true
app.email.override-recipient=${EMAIL_OVERRIDE_RECIPIENT}